// filepath: test/food_library_state_delete_guard_test.dart
//
// Regression tests for the **delete-category-must-not-leave-foods-
// stranded** rule.
//
// Symptom: the user deletes a category from the Library's Groups
// tab. Foods filed under the category keep pointing at it.
// Bundled catalog foods cannot be moved to a different category
// by any path in the app, so deleting a category the bundled
// catalog uses strands every catalog food in it, permanently.
//
// Constraint: do not solve this by rewriting the `groupId` of a
// bundled catalog food. The catalog refresh restores the
// categories of bundled foods on launch, so any such change
// would silently revert and the user would watch their action
// undo itself.
//
// Fix: `FoodLibraryState.deleteFoodGroupReassigningFoods` now
// refuses the deletion when at least one bundled catalog food
// (`isBundledCatalogFood(id) == true`) has `groupId` matching
// the category being deleted. It throws a typed
// `FoodGroupHasBundledFoodsError` (a `StateError` subclass) so
// the UI can catch it and surface a snackbar. Non-bundled
// catalog foods (user-created via **+ New Item**) and library
// foods are reassigned as today.
//
// The non-bundled case (delete a category whose foods are all
// user-created / library) is preserved as-is. S-007 pins it.

import 'package:flutter_test/flutter_test.dart';

import 'package:omnitrain/core/models/food_draft.dart';
import 'package:omnitrain/data/models/models.dart';
import 'package:omnitrain/data/repositories/mock_workout_repository.dart';
import 'package:omnitrain/state/food_library_state.dart';

Future<MockWorkoutRepository> _freshRepo() async {
  final repo = MockWorkoutRepository();
  await repo.initialize();
  return repo;
}

Food _catalogFood({required String id, required String name, String? groupId}) {
  return Food(
    id: id,
    name: name,
    groupId: groupId,
    unitType: FoodUnitType.grams,
    referenceAmount: 100,
    referenceLabel: 'g',
    isCatalog: true,
    protein: 10,
    carbs: 5,
    fat: 1,
    createdAtMs: 1000,
    updatedAtMs: 1000,
  );
}

Food _libraryFood({required String id, required String name, String? groupId}) {
  return Food(
    id: id,
    name: name,
    groupId: groupId,
    unitType: FoodUnitType.grams,
    referenceAmount: 100,
    referenceLabel: 'g',
    isCatalog: false,
    protein: 10,
    carbs: 5,
    fat: 1,
    createdAtMs: 1000,
    updatedAtMs: 1000,
  );
}

void main() {
  group('FoodLibraryState.deleteFoodGroupReassigningFoods: bundled guard', () {
    test('throws FoodGroupHasBundledFoodsError when a bundled catalog food '
        'still points at the category (S-006)', () async {
      final repo = await _freshRepo();
      final state = FoodLibraryState(repo);

      // Seed: the bundled `food-group-dairy` exists, and a
      // bundled catalog food (any id from the bundled ids set
      // — `almond_milk` is one of them) points at it.
      await repo.seedCatalogFood(
        _catalogFood(
          id: 'almond_milk',
          name: 'Almond milk, unsweetened',
          groupId: 'food-group-dairy',
        ),
      );
      await state.loadCatalogFoods();
      await state.loadFoodGroups();

      expect(
        () => state.deleteFoodGroupReassigningFoods('food-group-dairy', null),
        throwsA(isA<FoodGroupHasBundledFoodsError>()),
      );
    });

    test(
      'leaves every food\'s groupId byte-identical when the deletion is refused '
      '(S-006)',
      () async {
        final repo = await _freshRepo();
        final state = FoodLibraryState(repo);

        await repo.seedCatalogFood(
          _catalogFood(
            id: 'almond_milk',
            name: 'Almond milk, unsweetened',
            groupId: 'food-group-dairy',
          ),
        );
        await state.loadCatalogFoods();
        await state.loadFoodGroups();

        try {
          await state.deleteFoodGroupReassigningFoods('food-group-dairy', null);
        } catch (_) {
          // expected
        }

        // The bundled food's groupId is unchanged.
        final reloaded = await repo.getCatalogFoodById('almond_milk');
        expect(reloaded, isNotNull);
        expect(reloaded!.groupId, 'food-group-dairy');

        // The category itself is not archived.
        final groups = await repo.getFoodGroups(includeArchived: true);
        final dairy = groups.firstWhere((g) => g.id == 'food-group-dairy');
        expect(dairy.isArchived, isFalse);
      },
    );

    test('reassigns and archives when only non-bundled catalog foods '
        'and library foods point at the category (S-007)', () async {
      final repo = await _freshRepo();
      final state = FoodLibraryState(repo);

      // Use a brand-new user-defined category so the bundled
      // guard does not fire on the seed catalog's bundled
      // `food-group-*` ids. The id is generated by
      // `createFoodGroup`, so capture it.
      await state.createFoodGroup('My Custom');
      final customId = state.foodGroups
          .firstWhere((g) => g.name == 'My Custom')
          .id;

      // Two user-created catalog foods (NOT in the bundled
      // ids set), one library food, all in the custom group.
      await state.createCatalogFood(
        FoodDraft(
          name: 'Custom 1',
          groupId: customId,
          unitType: FoodUnitType.grams,
          referenceAmount: 100,
          referenceLabel: 'g',
          protein: 5,
          carbs: 1,
          fiber: null,
          fat: 0.5,
          sodium: null,
          notes: null,
          imagePath: null,
        ),
      );
      await state.createCatalogFood(
        FoodDraft(
          name: 'Custom 2',
          groupId: customId,
          unitType: FoodUnitType.grams,
          referenceAmount: 100,
          referenceLabel: 'g',
          protein: 6,
          carbs: 2,
          fiber: null,
          fat: 0.6,
          sodium: null,
          notes: null,
          imagePath: null,
        ),
      );
      await state.createFood(
        _libraryFood(id: 'lib-1', name: 'Library 1', groupId: customId),
      );

      await state.loadFoodGroups();
      await state.loadCatalogFoods();
      await state.loadFoods();

      // Delete with destination = null (Ungrouped). All
      // three rows should reassign to null and the group
      // should archive.
      await state.deleteFoodGroupReassigningFoods(customId, null);

      // The user-created catalog foods now have groupId null.
      final customs = state.catalogFoods
          .where((f) => f.name == 'Custom 1' || f.name == 'Custom 2')
          .toList();
      expect(customs, hasLength(2));
      for (final c in customs) {
        expect(c.groupId, isNull);
      }
      // The library food has groupId null.
      final lib = state.foods.firstWhere((f) => f.id == 'lib-1');
      expect(lib.groupId, isNull);
      // The category is archived.
      final group = state.foodGroups.firstWhere((g) => g.id == customId);
      expect(group.isArchived, isTrue);
    });

    test('allows deletion when no bundled catalog food still has the '
        'group\'s id, even if other bundled foods exist in the repo '
        '(S-006 negative)', () async {
      final repo = await _freshRepo();
      final state = FoodLibraryState(repo);

      // Create a brand-new user-defined category that is
      // guaranteed to be empty of bundled foods (the seed
      // catalog only files under the 9 default
      // `food-group-*` ids, so any other id is empty). This
      // is the realistic "delete a category with no
      // bundled foods" path — the bundled foods in the
      // repo are simply filed under the *default* groups.
      await state.createFoodGroup('Empty Custom');
      final emptyId = state.foodGroups
          .firstWhere((g) => g.name == 'Empty Custom')
          .id;
      await state.loadFoodGroups();

      // No bundled food points at the empty group →
      // deletion succeeds (the guard does not fire).
      await state.deleteFoodGroupReassigningFoods(emptyId, null);
      final groups = await repo.getFoodGroups(includeArchived: true);
      final empty = groups.firstWhere((g) => g.id == emptyId);
      expect(empty.isArchived, isTrue);
    });
  });
}
